In [2]:
import pandas as pd

In [8]:
df = pd.read_csv("backend/app/services/scraping/universities/data/universidades_pre_llm.csv")
df

,name,website,province,type,url_about_us,clean_text
0,Universidad de Almería,https://www.ual.es,Almería,Pública,https://www.ual.es/planestrategico,Plan Estratégico 2025 - 2027 - Universidad de ...
1,Universidad de Cádiz,https://www.uca.es,Cádiz,Pública,https://www.uca.es/historia/,Historia de la Universidad de Cádiz – Portal U...
2,Universidad de Córdoba,http://www.uco.es,Córdoba,Pública,https://www.uco.es/historia-y-video-promociona...,Historia y vídeo promocional | Universidad de ...
3,Universidad Loyola Andalucía,https://www.uloyola.es,Córdoba,Privada,https://www.uloyola.es/universidad/quienes-som...,Identidad y Misión\nUniversidad Loyola\n×\nbus...
4,Universidad de Granada,https://www.ugr.es,Granada,Pública,https://www.ugr.es/universidad/organizacion/sa...,Saludo del Rector | Universidad de Granada\nPa...
...,...,...,...,...,...,...
70,Euskal Herriko Unibertsitatea,http://www.ehu.es,Bizkaia,Pública,https://www.euskampus.eus/es/campus/misiones/m...,BIZI-ON | Euskampus Fundazioa\nPasar al conten...
71,Mondragon Unibertsitatea,http://www.mondragon.edu,Gipuzkoa,Privada,http://www.mondragon.edu/es/informacion/admisi...,Admisiones - Mondragon Unibertsitatea\nConsent...
72,Universidad Católica San Antonio de Murcia,http://www.ucam.edu,Murcia,Privada,https://www.ucam.edu/admision,Admisión | UCAM Universidad Católica de Murcia...
73,Universidad de Murcia,http://www.um.es,Murcia,Pública,https://www.um.es/web/universidad/historia,Historia de la Universidad de Murcia - Univers...
74,Universidad Politécnica de Cartagena,http://www.upct.es,Murcia,Pública,https://admision.upct.es/#preinscripcion-y-mat...,Admisión | Universidad Politécnica de Cartagen...

In [ ]:
# ---------------  PROMPT --------------- #
PROMPT = """

Descripción:
{texto}
"""


# ---------------  CONFIGURACIÓN --------------- #
MODEL = "gpt-oss:120b-cloud"
API_KEY = "95d420411abf4d779651adc5b09480b6.ZRboNs9BwdTvj_1mMmoXdNhQ"

client = Client(
    host="https://ollama.com",
    headers={'Authorization': 'Bearer ' + API_KEY}
)


def extract_info_cloud(texto: str) -> dict:
    mensaje = PROMPT.format(texto=texto)
    try:
        response = client.chat(
            model=MODEL,
            messages=[{'role': 'user', 'content': mensaje}],
            stream=False
        )
        content = response['message']['content']
        return json.loads(content)
    except Exception as e:
        print("ERROR LLM:", e)
        print("CONTENT RECIBIDO:", content if 'content' in locals() else None)
        return {
            "experience_required": "",
            "education_required": "",
            "skills_must": [],
            "skills_nice": [],
            "seniority": "",
            "job_type": "",
            "tech_stack": [],
            "soft_skills": [],
            "languages": [],
            "benefits": [],
            "category": ""
        }

In [4]:
import os
os.chdir("/Users/pablotutorlopez/Desktop/CARPETAS/Match_Key_Mavericks/MatchKey-GenAI-Maverick")

In [9]:
df = pd.read_json("backend/app/services/scraping/universities/data/universities_final.json", orient="records")
df.head()

,name,website,province,type,url_about_us,clean_text,university_name,values,mission,vision,culture_summary
0,Universidad de Almería,https://www.ual.es,Almería,Pública,https://www.ual.es/planestrategico,Plan Estratégico 2025 - 2027 - Universidad de ...,Universidad de Almería,"[innovación, sostenibilidad, responsabilidad s...",Promover la generación de conocimiento y la fo...,Convertirse en una universidad de referencia i...,Una cultura que favorece la libertad de pensam...
1,Universidad de Cádiz,https://www.uca.es,Cádiz,Pública,https://www.uca.es/historia/,Historia de la Universidad de Cádiz – Portal U...,Universidad de Cádiz,"[Calidad educativa, Investigación e innovación...",Formar profesionales y ciudadanos con alto niv...,Consolidarse como una universidad de referenci...,La Universidad de Cádiz combina una tradición ...
2,Universidad de Córdoba,http://www.uco.es,Córdoba,Pública,https://www.uco.es/historia-y-video-promociona...,Historia y vídeo promocional | Universidad de ...,Universidad de Córdoba,"[Calidad docente, Solvencia científica, Invest...",Formar profesionales con alta calidad docente ...,Ser una universidad de referencia en Andalucía...,"Cultura dinámica y orientada a la excelencia, ..."
3,Universidad Loyola Andalucía,https://www.uloyola.es,Córdoba,Privada,https://www.uloyola.es/universidad/quienes-som...,Identidad y Misión\nUniversidad Loyola\n×\nbus...,Universidad Loyola,"[Pasión por conocer, Excelencia, Exigencia, Se...",Crear pensamiento para el mejor y mayor servic...,Ser una Doctoral Research University reconocid...,Universidad Jesuita orientada a la investigaci...
4,Universidad de Granada,https://www.ugr.es,Granada,Pública,https://www.ugr.es/universidad/organizacion/sa...,Saludo del Rector | Universidad de Granada\nPa...,Universidad de Granada,"[igualdad, inclusión, diversidad, innovación, ...","Brindar una educación, investigación y transfe...",Convertirse en una universidad líder a nivel m...,Una comunidad diversa de más de 63 000 persona...

In [7]:
df

,name,website,province,type,url_about_us,clean_text,university_name,values,mission,vision,culture_summary
0,Universidad de Almería,https://www.ual.es,Almería,Pública,https://www.ual.es/planestrategico,Plan Estratégico 2025 - 2027 - Universidad de ...,Universidad de Almería,[],Promover la generación de conocimiento y la fo...,"Convertirse en una universidad más humana, inn...",La Universidad de Almería fomenta una cultura ...
1,Universidad de Cádiz,https://www.uca.es,Cádiz,Pública,https://www.uca.es/historia/,Historia de la Universidad de Cádiz – Portal U...,Universidad de Cádiz,[],,,
2,Universidad de Córdoba,http://www.uco.es,Córdoba,Pública,https://www.uco.es/historia-y-video-promociona...,Historia y vídeo promocional | Universidad de ...,Universidad de Córdoba,"[Docencia, Investigación, Calidad, Europa]",,,La Universidad de Córdoba se presenta como una...
3,Universidad Loyola Andalucía,https://www.uloyola.es,Córdoba,Privada,https://www.uloyola.es/universidad/quienes-som...,Identidad y Misión\nUniversidad Loyola\n×\nbus...,Universidad Loyola,"[Pasión por conocer, Excelencia, Exigencia, Se...",Crear pensamiento para el mejor y mayor servic...,Ser una Doctoral Research University reconocid...,Universidad Loyola se define por una cultura j...
4,Universidad de Granada,https://www.ugr.es,Granada,Pública,https://www.ugr.es/universidad/organizacion/sa...,Saludo del Rector | Universidad de Granada\nPa...,Universidad de Granada,"[igualdad, inclusión, seguridad, innovación, d...",Ofrecer un entorno digital y presencial que fa...,"Ser una universidad abierta al mundo, líder in...",Una comunidad universitaria diversa de más de ...
...,...,...,...,...,...,...,...,...,...,...,...
70,Euskal Herriko Unibertsitatea,http://www.ehu.es,Bizkaia,Pública,https://www.euskampus.eus/es/campus/misiones/m...,BIZI-ON | Euskampus Fundazioa\nPasar al conten...,Universidad del País Vasco / Euskal Herriko Un...,"[Movilizar y empoderar a la ciudadanía, Cuidad...",Extender el apoyo a las personas con cáncer má...,Una sociedad vasca en la que el cáncer se afro...,"Cultura colaborativa, interdisciplinaria y par..."
71,Mondragon Unibertsitatea,http://www.mondragon.edu,Gipuzkoa,Privada,http://www.mondragon.edu/es/informacion/admisi...,Admisiones - Mondragon Unibertsitatea\nConsent...,Mondragon Unibertsitatea,[],,,Desde 1997 Mondragon Unibertsitatea ha estado ...
72,Universidad Católica San Antonio de Murcia,http://www.ucam.edu,Murcia,Privada,https://www.ucam.edu/admision,Admisión | UCAM Universidad Católica de Murcia...,UCAM Universidad Católica de Murcia,"[Docencia, Investigación, Evangelización, Depo...",,,
73,Universidad de Murcia,http://www.um.es,Murcia,Pública,https://www.um.es/web/universidad/historia,Historia de la Universidad de Murcia - Univers...,Universidad de Murcia,[],,,
74,Universidad Politécnica de Cartagena,http://www.upct.es,Murcia,Pública,https://admision.upct.es/#preinscripcion-y-mat...,Admisión | Universidad Politécnica de Cartagen...,Universidad Politécnica de Cartagena,"[Admisión, DESCUBRE UPCT, PRUEBAS DE ACCESO, P...",,,

In [11]:
df = pd.read_csv("backend/app/services/scraping/companies/data/companies_and_links.csv")
df.head()

             company                                       url_about_us
0  NTT America, Inc.                   https://www.global.ntt/about-us/
1  NTT America, Inc.  https://www.henneo.com/quienes-somos/mision-vi...
2  NTT America, Inc.  https://www.caixabank.com/es/sobre-nosotros/co...
3  NTT America, Inc.                 https://www.getnet.eu/sobre-getnet
4  NTT America, Inc.              https://www.merlindp.com/en/merliners

In [24]:
df = pd.read_csv("backend/app/services/scraping/companies/data/companies_pre_llm.csv")
df = df.drop_duplicates(subset="url_about_us")
df.head()

,company,url_about_us,clean_text
0,"NTT America, Inc.",https://www.global.ntt/about-us/,NTT About Us – Driving Global Innovation and S...
1,Henneo,https://www.henneo.com/quienes-somos/mision-vi...,"Misión, visión y valores | HENNEO\nCon tu cons..."
2,Caixabank Digital Hub,https://www.caixabank.com/es/sobre-nosotros/co...,"Misión, visión, valores\n| CaixaBank\nanalizar..."
3,Getnet,https://www.getnet.eu/sobre-getnet,Sobre Nosotros | Getnet\nPagos en persona\nEn ...
4,Merlin Digital Partner,https://www.merlindp.com/en/merliners,Merliners - Merlin Digital partner\nES\n|\nEN\...